name: Build Image and Test with Snyk

on:
  push:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3

        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3

        # - name: Login to Docker Hub
        #   uses: docker/login-action@v3
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        # - name: Build and push
        #   uses: docker/build-push-action@v5
        #   with:
        #     push: true
            # tags: troysnyk/snyk-juice-shop:linux

        - uses: snyk/actions/setup@master
        - name: Snyk Container Monitor 
          run: snyk container monitor troysnyk/snyk-juice-shop:linux --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}" --org=${{ secrets.SNYK_ORG_ID }} --exclude-app-vulns --file=Dockerfile
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
